apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-all-z
  name: node-all-z
  namespace: node-test
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: node-all-z
  type: LoadBalancer