apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-all-x
  name: node-all-x
  namespace: node-test
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: node-all-x
  type: LoadBalancer